// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/landing-page": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/landing-page";
  };
  "pages/Login.tsx": {
    id: "pages/Login";
    page: "/login";
  };
  "pages/LandingPage.tsx": {
    id: "pages/LandingPage";
    page: "/landing-page";
  };
};